openapi: 3.1.0
info:
  title: AIP Transparency Log
  version: 0.1.0
  description: |
    Append-only transparency log for the Agent Identity Protocol.
    
    Provides auditable record of identity events with Merkle tree proofs.
  license:
    name: MIT

servers:
  - url: http://localhost:8081
    description: Local development
  - url: https://log.aip.network
    description: Public log (future)

tags:
  - name: Info
    description: Log information
  - name: Entries
    description: Log entry operations
  - name: Proofs
    description: Inclusion proofs

paths:
  /health:
    get:
      tags: [Info]
      summary: Health check
      operationId: health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  service:
                    type: string
                    example: log

  /log/info:
    get:
      tags: [Info]
      summary: Get log information
      operationId: info
      responses:
        '200':
          description: Log information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogInfo'

  /log/entry/{sequence}:
    get:
      tags: [Entries]
      summary: Get a log entry by sequence number
      operationId: getEntry
      parameters:
        - name: sequence
          in: path
          required: true
          description: Sequence number (0-indexed)
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: Log entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogEntry'
        '404':
          description: Entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /log/did/{did}:
    get:
      tags: [Entries]
      summary: Get all entries for a DID
      operationId: getByDid
      parameters:
        - name: did
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of log entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LogEntry'

  /log/entry:
    post:
      tags: [Entries]
      summary: Append a new entry to the log
      operationId: appendEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewLogEntry'
      responses:
        '201':
          description: Entry appended
          content:
            application/json:
              schema:
                type: object
                properties:
                  sequence:
                    type: integer
                  entryHash:
                    type: string
        '400':
          description: Invalid entry or signature
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /log/proof/{sequence}:
    get:
      tags: [Proofs]
      summary: Get inclusion proof for an entry
      operationId: getProof
      parameters:
        - name: sequence
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Inclusion proof
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InclusionProof'
        '404':
          description: Entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    LogInfo:
      type: object
      properties:
        size:
          type: integer
          description: Number of entries in the log
        rootHash:
          type: string
          description: Merkle tree root hash
        operatorDid:
          type: string
          description: DID of the log operator

    LogEntry:
      type: object
      properties:
        sequence:
          type: integer
          description: Entry sequence number (0-indexed)
        timestamp:
          type: string
          format: date-time
        eventType:
          type: string
          enum: [identity_created, document_updated, key_rotation, key_revocation, root_recovery, recovery_cancelled]
        subjectDid:
          type: string
          description: DID this event relates to
        payload:
          type: object
          description: Event-specific payload
        previousHash:
          type: string
          description: Hash of previous entry
        entryHash:
          type: string
          description: Hash of this entry
        subjectSignature:
          type: string
          description: Signature from subject
        operatorSignature:
          type: string
          description: Signature from log operator

    NewLogEntry:
      type: object
      required: [eventType, subjectDid, payload, subjectSignature]
      properties:
        eventType:
          type: string
          enum: [identity_created, document_updated, key_rotation, key_revocation, root_recovery, recovery_cancelled]
        subjectDid:
          type: string
        payload:
          type: object
        subjectSignature:
          type: string

    InclusionProof:
      type: object
      properties:
        sequence:
          type: integer
        entryHash:
          type: string
        treeSize:
          type: integer
          description: Size of tree when proof was generated
        rootHash:
          type: string
          description: Root hash at time of proof
        proofPath:
          type: array
          items:
            $ref: '#/components/schemas/ProofNode'

    ProofNode:
      type: object
      properties:
        hash:
          type: string
        position:
          type: string
          enum: [left, right]
